Identity Application Assignment/Models/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Identity_Application_Assignment.Models
{
    public class RoleController : Controller
    {

        private readonly RoleManager<IdentityRole> _role;
        UserManager<ApplicationUser> _user;

        public RoleController(RoleManager<IdentityRole> role, UserManager<ApplicationUser> user)
        {
            _role = role;
            _user = user;

        }
        public IActionResult Index()
        {
            var roles = _role.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }


        //endpoint to create role
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                var result = await _role.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(role);
        }

        //endpoint for edit role
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _role.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        //edit post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, IdentityRole role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var existingRole = await _role.FindByIdAsync(id);
                if (existingRole == null)
                {
                    return NotFound();
                }

                existingRole.Name = role.Name;
                var result = await _role.UpdateAsync(existingRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(role);
        }

        //endpoint for delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _role.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _role.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            // Check if the role is assigned to any users
            var usersWithRole = await _user.GetUsersInRoleAsync(role.Name);

            if (usersWithRole.Count > 0)
            {
                ModelState.AddModelError("", "Cannot delete role because it is assigned to one or more users.");
            }
            else
            {
                var result = await _role.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View("Delete", role);
        }
    }
}

Identity Application Assignment/Controllers/UserController.cs
using Identity_Application_Assignment.Models;
using Identity_Application_Assignment.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Identity_Application_Assignment.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public UserController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;

        }

        //geting users and their roles
        public IActionResult Index()
        {
            var users = _userManager.Users.ToList(); 

            var userViewModels = new List<UsersViewModel>();

            foreach (var user in users)
            {
                var userRoles = _userManager.GetRolesAsync(user).Result; 

                var userViewModel = new UsersViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    Name = user.Name,
                    Roles = userRoles
                };

                userViewModels.Add(userViewModel);
            }

            return View(userViewModels);
        }

        //endpoint to edit user
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var roles = await _roleManager.Roles.ToListAsync();
            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                Name = user.Name,
                Roles = roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name,
                    Selected = userRoles.Contains(r.Name)
                }).ToList()
            };

            return View(model);
        }

        //edit post method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user == null)
                {
                    return NotFound();
                }

                user.Name = model.Name;
                user.Email = model.Email;

                // Update user roles based on the selected roles in the list
                var userRoles = await _userManager.GetRolesAsync(user);

                // Remove user from unselected roles
                var rolesToRemove = userRoles.Except(model.RoleName);
                await _userManager.RemoveFromRolesAsync(user, rolesToRemove);

                // Add user to selected roles
                var rolesToAdd = model.RoleName.Except(userRoles);
                await _userManager.AddToRolesAsync(user, rolesToAdd);

                // Update user properties
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        // Delete action 
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            // Check if the user is in any roles and remove them
            var userRoles = await _userManager.GetRolesAsync(user);
            if (userRoles != null && userRoles.Any())
            {
                foreach (var role in userRoles)
                {
                    var results = await _userManager.RemoveFromRoleAsync(user, role);
                    if (!results.Succeeded)
                    {
                        ModelState.AddModelError("", "Failed to remove user from role.");
                        return View(user);
                    }
                }
            }

            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(user);
        }

    }
}

Identity Application Assignment/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<Identity_Application_Assignment.Models.ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Identity_Application_Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Identity_Application_Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Identity_Application_Assignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Manage Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Manage Users</a>
                            </li>
                        }

                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_loginAndRegisterPartial" />
                        </div>

                    </ul>
                
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Identity_Application_Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Identity Application Assignment/Views/Shared/_loginAndRegisterPartial.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<Identity_Application_Assignment.Models.ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    <form method="post" id="logoutForm" asp-action="Logoff" asp-controller="Account">
        <ul class="nav navbar-nav">
            <li class="text-dark nav-link">Hello,@User.Identity.Name!</li>
            <li><a class="text-dark nav-link" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav">
        <li class="nav-item">
            @*@Html.ActionLink("Sign Up","Register","Account",routeValues:null,htmlAttributes:new {id="registerLink"})*@
            @*<a class="nav-link text-dark" id="registerLink" asp-controller="Account" asp-action="Register">Register</a>*@
        </li>
        <li>
            @*@Html.ActionLink("Sign In","Login","Account",routeValues:null,htmlAttributes:new {id="loginLink"})*@
            <a class="nav-link text-dark" id="loginLink" asp-controller="Account" asp-action="Login">Login</a>
        </li>
    </ul>
}